NAME = " AMRITANSHU KUMAR SINGH "
print( " MY NAME IS ", NAME)
REGISTRATIONNO = " 12205421 "
print( " MY REGISTRATION NO IS ", REGISTRATIONNO)
CGPA = " 7.31 "
print(" MY CGPA IS ", CGPA)
DOB = " 21FEB 2000 "
print(" MY DOB IS ",DOB)
BIRTHPLACE = " KOLKATA "
print(" MY BIRTH PLACE IS ", BIRTHPLACE )

